### ISSUE TITLE
Understanding raw resistance

### ISSUE THREAD

**Issue by stas-sl** [sciosense/ENS160_driver#7]
Running ens160basic_std always prints `R HP1` equal to 1 Ohm. Is my instance faulty or is it a common issue?

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/4602302/221070400-1aaa0dee-af97-43a2-8b02-8c5ae093c706.png">

**Comment by stas-sl** [comment]
Can you also clarify why datasheet says that only 2 sensing elements are available via registers (R1<sub>raw</sub> and R4<sub>raw</sub>):
<img width="707" alt="image" src="https://user-images.githubusercontent.com/4602302/221238303-2262471a-494a-4771-aa70-f4aa8a6c2ebe.png">

However this driver seems to read resistance values for all 4 elements:
```cpp
// Read raw resistance values
if (IS_NEWGPR(status)) {
    newData = true;		
    this->read(_slaveaddr, ENS160_REG_GPR_READ_0, i2cbuf, 8);
    _hp0_rs = CONVERT_RS_RAW2OHMS_F((uint32_t)(i2cbuf[0] | ((uint16_t)i2cbuf[1] << 8)));
    _hp1_rs = CONVERT_RS_RAW2OHMS_F((uint32_t)(i2cbuf[2] | ((uint16_t)i2cbuf[3] << 8)));
    _hp2_rs = CONVERT_RS_RAW2OHMS_F((uint32_t)(i2cbuf[4] | ((uint16_t)i2cbuf[5] << 8)));
    _hp3_rs = CONVERT_RS_RAW2OHMS_F((uint32_t)(i2cbuf[6] | ((uint16_t)i2cbuf[7] << 8)));
}
```

Also it is not clear why the datasheet for all gases refers to a single R4<sub>raw</sub> = GPR_READ[6:7]. What is the purpose of other sensing elements 1-3? What is the difference between them? Do they react to specific gases?

<img width="731" alt="image" src="https://user-images.githubusercontent.com/4602302/221241158-e683e29e-8713-4998-9836-4887695eea7e.png">

**Comment by rishi-a** [comment]
@stas-sl did you find any resolution to your issue? Asking because I have the same doubt.

**Comment by stas-sl** [comment]
Nope, but TBH I don't think it can differentiate between different gases. Even for CO2 it works quite disappointing. I'm comparing it with Senseair S8, and measurements are often mismatch. I mean not only absolute values, that could be understandable, but even trend/direction of change. I know that it could react to other organic compounds, but this doesn't explain why if CO2 is rising, ENS160 readings are decreasing (or stuck at some level).

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/4602302/228045964-f9469c35-fac4-4de4-897f-b05073df8799.png">

**Comment by rishi-a** [comment]
Thats dissapointing. Did you keep the sensor on for over and hour and than check? I believe some or all MOX sensors require a heating up and works well after that.

**Comment by stas-sl** [comment]
Sure, those sensors are running side by side continuously for over a month already.

**Comment by patryk02** [comment]
Hi,
a MOX sensor is NOT an CO2 sensor.
The eCO2 output of the ENS160 is an "equvalent CO2" level. It isNOT a real
CO2 level.
Based on the working principle, MOX sensors are not selective to reducing
or oxidising gases and their are NOT sensitive CO2 levels.
Based on some algorithms and training data sets, MOX sensors are capable of
predicting air quality levels like eCO2 prediction, TVOC prediction, AQI
index prediction.

**Comment by stas-sl** [comment]
Here is weekly resistance measurements for 3 of its hotplates (4th is zero):
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/4602302/228068547-41981683-7038-45cd-8b7e-d67502167c28.png">
As you can see they differ in absolute values, but are almost perfectly correlated. So probably all 4 sensing elements have a little bit different configuration, but are more or less identical.

**Comment by stas-sl** [comment]
@patryk02, what is the purpose having 4 hot plates if they are not selective to any of gases? Do they really improve accuracy on you training data comparing to using just one of them?

**Comment by patryk02** [comment]
Hi,
each hotplate operates at different conditions or a different sensing
material is deposited on it.
This small differences cause a slightly different behaviour and variations
in sensing layer resistance.
These small differences are used by the algorithm to calculate the eCO2,
TVOC values and predict the indoor air quality.

**Comment by flisboac** [comment]
I understand that eCO2 is an estimate, that tVOC doesn't allow for distinguishing between a specific chemical compound from another, and all of that.

However, I have a question: what's the purpose of custom modes? The datasheet alludes to the possibility of improving the sensor's response to specific gases. Quote from the datasheet:

> Measurement values for individual gases can be obtained from dedicated device registers or
calculated from sensor raw resistance values as specified in above table.

But no instruction is given about:

- Which resistances (or combination of resistances) are responsible for measuring a specific gas;
- What each register is responsible for (fortunately, we have the source code to give us clues about that, but still, official documentation is not clear on that at all); and
- How to manipulate the registers to achieve a specific outcome/sensibility profile (e.g. correlation between hotplate temperature + time and measurement resistance).

The custom mode example doesn't state its reason for existing. I mean, I know it's meant to show how to configure and use custom modes, but why is it needed? What is it focused on measuring? None of those questions are answered in the example, so we're left with the impression that the custom mode implementation has no practical use. Which is a shame, because no other sensor does what ENS160 does (or at least it's not marketed as such), and I initially was thrilled to use the sensor for this exact purpose (e.g. sensitize towards a specific gas depending on an ambient event, etc., which would allow some reduction in BOM).

**Comment by NathanSweet** [comment]
@flisboac I'd love to see Sciosense more involved. Barring that, BME688 can sense a specific gas (roughly, I assume).

**Comment by flisboac** [comment]
> @flisboac I'd love to see Sciosense more involved. Barring that, BME688 can sense a specific gas (roughly, I assume).

I checked out the BME688, but they force you to use a proprietary and closed-source library just to get basic information like TVOC, AQI, etc. It's a pain to integrate into a build system, not to mention the need to accept and uphold yet another terms of use (which is not clear, in some regards).

In that sense, the ENS160 is a better solution, because there's no closed-source nonsense nor legalese limitations to deal with. It's much more consumer-friendly. Also, the documentation is, for the most part, so much clearer and to the point, in the sense that I can easily find what I need.

That said, custom mode is the only undocumented feature that I really wish they would give some more attention to. Perhaps a new Application Note could solve it. It's the only thing missing for the ENS160 to be the perfect TVOC solution.

**Comment by webseitz** [comment]
Custom mode is meant for customers developing an algorithm by them own, which needs a lot of specific knowledge and testing. Please have a look at available publications, there is a lot of scientific literature of MOX temperature modulation and its effect to sensitivity and selectivity.
